### ISSUE TITLE
请教如何修改配置文件自定义cron时间

### ISSUE THREAD

**Issue by AIEOV** [CaoMeiYouRen/rss-impact-server#139]
Docker Compose 方式部署   
看示例站最小10min  想设置10s 
搜索到rss-cron.ts这个文件表示的  但是不会修改 
请指教谢谢

**Comment by CaoMeiYouRen** [comment]
我想先问下，什么情况下会需要 10s 的轮询时间？

**Comment by AIEOV** [comment]
> 我想先问下，什么情况下会需要 10s 的轮询时间？

监控些奇奇怪怪的西 稍纵即逝的  
可否请求增加短时间选项
或者增加以环境变量形式自定义cron  可以适应更多用途

**Comment by CaoMeiYouRen** [comment]
> > 我想先问下，什么情况下会需要 10s 的轮询时间？
> 
> 监控些奇奇怪怪的西 稍纵即逝的 可否请求增加短时间选项 或者增加以环境变量形式自定义cron 可以适应更多用途

这很大程度上取决于源站提供的 RSS 订阅内容的更新。
如果源站设置了缓存，轮询时间再短也是没用的。
