### ISSUE TITLE
[bug] 无法登录

### ISSUE THREAD

**Issue by bandaot** [CaoMeiYouRen/rss-impact-server#438]
**Describe the bug/描述 bug**

A clear and concise description of what the bug is.<br/>
对 bug 是什么的清晰简洁的描述。
使用docker composer部署之后，无法登录，查看请求发现login API成功，但/me提示用户未登录。看log是login没有返回cookie
---
**To Reproduce/再现**

Steps to reproduce the behavior:<br/>
再现行为的步骤：
打开登录页，输入账号密码
---
**Expected behavior/预期行为**

A clear and concise description of what you expected to happen.<br/>
对你期望发生的事情的清晰简洁的描述
完成登录进入系统
---
**Screenshots/屏幕截图**

If applicable, add screenshots to help explain your problem.<br/>
如果适用，请添加屏幕截图以帮助解释您的问题。

---
**Desktop (please complete the following information):/系统信息（请填写以下信息）：**

 - OS: [e.g. Windows 10, macOS 11.2, Ubuntu 20.04, Docker]
 - Browser: [e.g., Chrome 91, Firefox 89]
 - NodeJS Version: [e.g. 20.0.0]
 - RSS Impact Version [e.g. 1.0.0]

---
**Additional context/附加上下文**

Add any other context about the problem here.<br/>
在此处添加有关该问题的任何其他上下文

---
**Paid Consultation/付费咨询**

如果您愿意支付费用以获得更快的回复，请[前往爱发电进行赞助](https://afdian.com/a/CaoMeiYouRen)<br/>
如果您不愿意付费，请耐心等待开发者回复。开发者可能因为各种各样的原因无法及时回复，还请谅解。

**Comment by CaoMeiYouRen** [comment]
如果可以的话，请提供一下前端和后端接口的日志和堆栈信息，以排查问题。

如果你是通过docker在本地部署的，请参照部署文档中的环境变量配置一节排查问题

**Comment by wj-zecoba** [comment]
我启动了本地开发环境，总算看到log了，是SQLite没有写入权限。我直接用docker compose启动的，不知道为啥，加上权限就好了。

**Comment by CaoMeiYouRen** [comment]
> 我启动了本地开发环境，总算看到log了，是SQLite没有写入权限。我直接用docker compose启动的，不知道为啥，加上权限就好了。

你好，可以提供更多信息吗？例如堆栈、日志等

**Comment by CaoMeiYouRen** [comment]
经过排查，是出现了跨域，请在环境变量中设置 `ENABLE_ORIGIN_LIST`，例如
```.env
ENABLE_ORIGIN_LIST='http://localhost:3000,http://127.0.0.1:3000'
```
